server:
  port: 8090

token:
  header: Authorization
  secret:
  expireTime: 480

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://10.10.10.102:3307/wboot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: eLe9Vrg98hFdhhB
springdoc:
  packages-to-scan:
    - top.watilion.wboot.system.controller
    - top.watilion.wboot.common
  paths-to-match:
    - /system/**
    - /v1
